### ISSUE TITLE
When I try to pull in the nuget package as a local it fails

### ISSUE THREAD

**Issue by nPowers** [ondrabus/kentico-auditor#1]
The package says it's Auditor module 2.0.0 and it fails to load from a local nuget path into a kentico 12.0.7 local instance of the code.  The site says it's Kentico Auditor 12.0.0 - was there a typo?  Can I just load the DLL's into bin and import the pages via the kentico import? Leaving the creation of the DB, which with a script or in the build of the auditor, could be in there. Haven't investigated the full solution.

**Comment by ondrabus** [comment]
Hi @nPowers, thanks for the report, I will check it out.

**Comment by nPowers** [comment]
When pulling the package into a kentico 12 portal aspx solution,  I get this error when pulling from a local nuget repo: 

Package 'AuditorModule 2.0.0' is not found in the following primary source(s): 'C:\Users\xxxxx\OneDrive\Documents\GitHub\kentico-auditor'. Please verify all your online package sources are available (OR) package id, version are specified correctly.  

I have tried non-onedrive sources as well.

**Comment by nPowers** [comment]
Any Updates?

**Comment by ondrabus** [comment]
Hi @nPowers, you were right, there was a typo and also package naming issue. Fixed it via https://github.com/ondrabus/kentico-auditor/commit/3d49caa6965bba25f76f33a634d8f60396859773 and tested - works OK for base Kentico 12.

**Comment by nPowers** [comment]
Send me a tree lol

**Comment by ondrabus** [comment]
@nPowers This is not officially supported by Kentico, so the bugs policy does not apply, but I'll send you a tree selfie 😃

**Comment by nPowers** [comment]
Perfect :)
